# Generated by Django 4.1.7 on 2023-02-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='Images')),
                ('link', models.CharField(max_length=250)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
