# Generated by Django 4.1.7 on 2023-02-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='manager',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='manager',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
