# Generated by Django 4.1.7 on 2023-02-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_alter_manager_options_manager_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='description',
            field=models.CharField(default='', max_length=250),
        ),
    ]
