# Generated by Django 4.1.7 on 2023-02-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_manager_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='static/user-images')),
                ('link', models.CharField(max_length=250)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
