# Generated by Django 4.1.7 on 2023-02-28 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_projects_delete_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(upload_to='user-images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='link',
            field=models.URLField(),
        ),
    ]
